name: MoneySplit
options:
  bundleIdPrefix: com.moneysplit
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    IPHONEOS_DEPLOYMENT_TARGET: "18.0"
    PRODUCT_BUNDLE_IDENTIFIER: com.moneysplit.app
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_STRICT_CONCURRENCY: complete
    ENABLE_TESTABILITY: YES
    DEBUG_INFORMATION_FORMAT: dwarf-with-dsym

targets:
  MoneySplit:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: MoneySplit
        createIntermediateGroups: true
    resources:
      - path: MoneySplit/Resources/Assets.xcassets
      - path: MoneySplit/Resources/Preview Content
    settings:
      base:
        INFOPLIST_FILE: MoneySplit/Resources/Info.plist
        PRODUCT_NAME: "Money Split"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_STRICT_CONCURRENCY: complete
    info:
      path: MoneySplit/Resources/Info.plist
      properties:
        CFBundleDisplayName: "Money Split"
        CFBundleName: "Money Split"
        UILaunchScreen:
          UIImageName: ""
          UIColorName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIRequiresFullScreen: false
        ITSAppUsesNonExemptEncryption: false

schemes:
  MoneySplit:
    build:
      targets:
        MoneySplit: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
